const event_types = [
    "Training Event",
    "Competition",
    "Workshop",
    "Conference",
    "Seminar",
    "Exhibition",
    "Trade Show",
    "Networking Event",
    "Cultural Festival",
    "Art Exhibition",
    "Music Festival",
    "Theater Performance",
    "Charity Gala",
    "Fundraising Auction",
    "Benefit Concert",
    "Marathon Race",
    "Community Fair",
    "Town Hall Meeting",
    "Volunteer Activity",
    "Party",
    "Concert",
    "Festival",
    "Product Launch",
    "Basketball Game",
    "Soccer Match",
    "Golf Tournament",
    "Health Fair",
    "Wellness Expo",
    "Fitness Challenge",
    "Tech Expo",
    "Innovation Showcase",
    "Environmental Awareness Event",
    "Sustainability Fair",
    "Fashion Show",
    "Science Fair",
    "Educational Expo",
    "Open House",
    "Wedding",
    "Anniversary Celebration",
    "Birthday Party",
    "Religious Ceremony",
    "Spiritual Retreat",
    "Yoga Retreat",
    "Food and Wine Festival",
    "Film Screening",
    "Book Launch",
    "Dance Performance",
    "Poetry Slam",
    "Classic Car Show",
    "Holiday Parade",
    "Motivational Seminar",
    "Government Policy Announcement",
    "Public Safety Campaign",
    "Agricultural Fair",
    "Government Summit",
    "National Day Celebration",
    "Independence Day Parade",
    "Election Rally",
    "Trade Delegation Meeting",
    "International Diplomatic Conference",
    "Infrastructure Development Expo",
    "Public Health Initiative",
    "Rural Development Program Launch",
]

export default event_types;